#!/bin/sh
# embed_cert.sh — generate src/tls/cert_data.S from certs/cert.der and
# certs/key.pem.
#
# PLAN.MD Phase 15 explicitly rules out a general X.509 parser: instead
# the certificate (DER) and the raw ECDSA P-256 private scalar are
# embedded into the binary at build time, the same way embed_www.sh
# turns www/ into src/embedded.S. Unlike embedded.S this doesn't use
# .incbin, because .incbin paths are resolved relative to the
# assembler's working directory, and this file gets assembled from two
# different directories (the top-level Makefile from the repo root,
# tests/unit/Makefile from tests/unit/) — a single relative path can't
# satisfy both. Literal .byte data has no such problem.
#
# Run this whenever certs/cert.der or certs/key.pem change (e.g. after
# ./generate.sh). Requires OpenSSL (for the private key) and python3
# (to format the .byte lines).
#
# Usage: ./embed_cert.sh

set -eu
cd "$(dirname "$0")"

OUTPUT="../src/tls/cert_data.S"
CERT_DER="cert.der"
KEY_PEM="key.pem"

[ -f "$CERT_DER" ] || { echo "embed_cert.sh: $CERT_DER not found (run ./generate.sh first)" >&2; exit 1; }
[ -f "$KEY_PEM" ] || { echo "embed_cert.sh: $KEY_PEM not found (run ./generate.sh first)" >&2; exit 1; }

# Raw 32-byte P-256 private scalar, one byte per line of "priv:" hex.
PRIV_HEX=$(openssl ec -in "$KEY_PEM" -noout -text 2>/dev/null \
    | sed -n '/^priv:/,/^pub:/p' | sed '1d;$d' | tr -d ' :\n')
PRIV_LEN=$(( ${#PRIV_HEX} / 2 ))
if [ "$PRIV_LEN" -ne 32 ]; then
    echo "embed_cert.sh: expected a 32-byte P-256 private scalar, got $PRIV_LEN bytes" >&2
    exit 1
fi

python3 - "$CERT_DER" "$PRIV_HEX" "$OUTPUT" <<'PYEOF'
import sys

cert_path, priv_hex, out_path = sys.argv[1:4]
with open(cert_path, "rb") as f:
    cert = f.read()
priv = bytes.fromhex(priv_hex)

def byte_lines(data, per_line=12):
    lines = []
    for i in range(0, len(data), per_line):
        chunk = data[i:i + per_line]
        lines.append("    .byte " + ", ".join("0x%02x" % b for b in chunk))
    return "\n".join(lines)

header = (
    "// Auto-generated by certs/embed_cert.sh from certs/cert.der and\n"
    "// certs/key.pem -- do not edit by hand.\n"
    "//\n"
    "// PLAN.MD Phase 15: the certificate (DER, RFC 8446 4.4.2 cert_data)\n"
    "// and the raw ECDSA P-256 private scalar this server signs\n"
    "// CertificateVerify with (Phase 16/17). No X.509 parser is\n"
    "// implemented or needed: cert_data is copied onto the wire\n"
    "// byte-for-byte, and the private key is only ever used as raw\n"
    "// ECDSA signing input.\n"
    "\n"
    ".data\n"
    ".align 4\n"
    ".global tls_cert_der\n"
    ".global tls_cert_der_end\n"
    "tls_cert_der:\n"
)

with open(out_path, "w") as f:
    f.write(header)
    f.write(byte_lines(cert) + "\n")
    f.write("tls_cert_der_end:\n\n")
    f.write(".align 4\n.global tls_priv_key\ntls_priv_key:\n")
    f.write(byte_lines(priv) + "\n")

print("wrote %s (%d-byte cert, %d-byte private key)" % (out_path, len(cert), len(priv)))
PYEOF
