#!/bin/sh
# embed_www.sh — generate src/embedded.S by embedding all www/ files into the binary.
# This script scans www/ recursively, determines MIME types by extension,
# and generates an assembly file with .incbin directives and a lookup table.

set -eu

WWW_DIR="www"
OUTPUT="src/embedded.S"

# ── MIME type map (mirrors file_types table in src/file.S) ────────────────
mime_type() {
    case "$1" in
        # web
        .html)  echo "text/html; charset=utf-8" ;;
        .htm)   echo "text/html; charset=utf-8" ;;
        .css)   echo "text/css; charset=utf-8" ;;
        .csv)   echo "text/csv; charset=utf-8" ;;
        .xml)   echo "text/xml; charset=utf-8" ;;
        .js)    echo "text/javascript; charset=utf-8" ;;
        .json)  echo "application/json" ;;
        .wasm)  echo "application/wasm" ;;
        .mjs)   echo "text/javascript; charset=utf-8" ;;
        .map)   echo "application/json" ;;
        # image
        .png)   echo "image/png" ;;
        .jpg)   echo "image/jpeg" ;;
        .jpeg)  echo "image/jpeg" ;;
        .gif)   echo "image/gif" ;;
        .svg)   echo "image/svg+xml" ;;
        .ico)   echo "image/x-icon" ;;
        .webp)  echo "image/webp" ;;
        .avif)  echo "image/avif" ;;
        .bmp)   echo "image/bmp" ;;
        .tiff)  echo "image/tiff" ;;
        .apng)  echo "image/apng" ;;
        # fonts
        .woff)  echo "font/woff" ;;
        .woff2) echo "font/woff2" ;;
        .ttf)   echo "font/ttf" ;;
        .otf)   echo "font/otf" ;;
        # documents
        .txt)   echo "text/plain; charset=utf-8" ;;
        .pdf)   echo "application/pdf" ;;
        .doc)   echo "application/msword" ;;
        .docx)  echo "application/vnd.openxmlformats-officedocument.wordprocessingml.document" ;;
        .epub)  echo "application/epub+zip" ;;
        .rtf)   echo "application/rtf" ;;
        # video
        .mp4)   echo "video/mp4" ;;
        .webm)  echo "video/webm" ;;
        .mkv)   echo "video/x-matroska" ;;
        .avi)   echo "video/x-msvideo" ;;
        .mov)   echo "video/quicktime" ;;
        # audio
        .mp3)   echo "audio/mpeg" ;;
        .ogg)   echo "audio/ogg" ;;
        .wav)   echo "audio/wav" ;;
        .flac)  echo "audio/flac" ;;
        .aac)   echo "audio/aac" ;;
        .m4a)   echo "audio/mp4" ;;
        .opus)  echo "audio/opus" ;;
        # archives
        .zip)   echo "application/zip" ;;
        .gz)    echo "application/gzip" ;;
        .tar)   echo "application/x-tar" ;;
        .7z)    echo "application/x-7z-compressed" ;;
        .bz2)   echo "application/x-bzip2" ;;
        .rar)   echo "application/vnd.rar" ;;
        # default
        *)      echo "text/plain; charset=utf-8" ;;
    esac
}

# ── Collect files (recursive, exclude .DS_Store and dirs) ────────────────
files=""
if [ -d "$WWW_DIR" ]; then
    # Use find for recursive listing, sort for deterministic output
    files=$(find "$WWW_DIR" -type f -not -name '.DS_Store' | sort)
fi

# ── Generate assembly ─────────────────────────────────────────────────────
{
    echo '// Auto-generated by embed_www.sh — do not edit by hand.'
    echo '// Embeds all files from www/ into the binary data section.'
    echo ''
    echo '.data'
    echo '.align 3'
    echo ''

    i=0
    entry_count=0
    for f in $files; do
        ext=".${f##*.}"
        # Handle files with no extension or dotfiles
        if [ "$ext" = ".$f" ] || [ "$ext" = "." ]; then
            ext=""
        fi
        ct=$(mime_type "$ext")

        echo "embedded_path_${i}:"
        echo "    .asciz \"$f\""
        echo "embedded_path_${i}_end:"
        echo ''
        echo "embedded_ct_${i}:"
        echo "    .asciz \"$ct\""
        echo "embedded_ct_${i}_end:"
        echo ''
        echo "embedded_data_${i}:"
        echo "    .incbin \"$f\""
        echo "embedded_data_${i}_end:"
        echo ''

        i=$((i + 1))
        entry_count=$((entry_count + 1))
    done

    echo '.align 3'
    echo '.global embedded_files'
    echo 'embedded_files:'

    i=0
    for f in $files; do
        echo "    .8byte embedded_path_${i}, (embedded_path_${i}_end - embedded_path_${i} - 1)"
        echo "    .8byte embedded_data_${i}, (embedded_data_${i}_end - embedded_data_${i})"
        echo "    .8byte embedded_ct_${i},   (embedded_ct_${i}_end - embedded_ct_${i} - 1)"
        i=$((i + 1))
    done

    # Sentinel entry
    echo '    .8byte 0   // sentinel — end of table'
} > "$OUTPUT"

echo "Generated $OUTPUT with $entry_count embedded file(s)."
