#!/bin/sh
# embed_www.sh — generate src/embedded.S by embedding all www/ files into the binary.
# This script scans www/ recursively, determines MIME types by extension,
# computes SHA-256 hashes for ETag generation, and generates an assembly file
# with .incbin directives and a lookup table.
# For text-like files, gzip is applied if it reduces size; browsers will
# decompress transparently via Content-Encoding: gzip.
# Stage 4: FNV-1a hash-based lookup table for O(log n) file resolution.

set -eu

WWW_DIR="www"
OUTPUT="src/embedded.S"
FLAGS=$(mktemp /tmp/sarm_flags_XXXXXX)
trap 'rm -f "$FLAGS"' EXIT

# Persistent gzip cache dir — must outlive this script for the assembler.
GZCACHEDIR="www_gz"
mkdir -p "$GZCACHEDIR"

# ── Pick the available SHA-256 tool ──────────────────────────────────
if command -v shasum >/dev/null 2>&1; then
    SHA256="shasum -a 256"
elif command -v sha256sum >/dev/null 2>&1; then
    SHA256="sha256sum"
else
    echo "embed_www.sh: need shasum or sha256sum for ETag computation" >&2
    exit 1
fi

# ── FNV-1a 64-bit hash (matches fnv1a_64 in src/util/fnv1a_64.S) ────────
if ! command -v python3 >/dev/null 2>&1; then
    echo "embed_www.sh: need python3 for FNV-1a hash computation" >&2
    exit 1
fi

fnv1a() {
    python3 -c "
import sys
data = sys.argv[1].encode()
h = 0xcbf29ce484222325
for b in data:
    h ^= b
    h = (h * 0x100000001b3) & 0xffffffffffffffff
print(h)
" "$1"
}

# ── MIME type map (mirrors file_types table in src/file/get_filetype.S) ───────
mime_type() {
    case "$1" in
        # web
        .html)  echo "text/html; charset=utf-8" ;;
        .htm)   echo "text/html; charset=utf-8" ;;
        .css)   echo "text/css; charset=utf-8" ;;
        .csv)   echo "text/csv; charset=utf-8" ;;
        .xml)   echo "text/xml; charset=utf-8" ;;
        .js)    echo "text/javascript; charset=utf-8" ;;
        .json)  echo "application/json" ;;
        .wasm)  echo "application/wasm" ;;
        .mjs)   echo "text/javascript; charset=utf-8" ;;
        .map)   echo "application/json" ;;
        # image
        .png)   echo "image/png" ;;
        .jpg)   echo "image/jpeg" ;;
        .jpeg)  echo "image/jpeg" ;;
        .gif)   echo "image/gif" ;;
        .svg)   echo "image/svg+xml" ;;
        .ico)   echo "image/x-icon" ;;
        .webp)  echo "image/webp" ;;
        .avif)  echo "image/avif" ;;
        .bmp)   echo "image/bmp" ;;
        .tiff)  echo "image/tiff" ;;
        .apng)  echo "image/apng" ;;
        # fonts
        .woff)  echo "font/woff" ;;
        .woff2) echo "font/woff2" ;;
        .ttf)   echo "font/ttf" ;;
        .otf)   echo "font/otf" ;;
        # documents
        .txt)   echo "text/plain; charset=utf-8" ;;
        .pdf)   echo "application/pdf" ;;
        .doc)   echo "application/msword" ;;
        .docx)  echo "application/vnd.openxmlformats-officedocument.wordprocessingml.document" ;;
        .epub)  echo "application/epub+zip" ;;
        .rtf)   echo "application/rtf" ;;
        # video
        .mp4)   echo "video/mp4" ;;
        .webm)  echo "video/webm" ;;
        .mkv)   echo "video/x-matroska" ;;
        .avi)   echo "video/x-msvideo" ;;
        .mov)   echo "video/quicktime" ;;
        # audio
        .mp3)   echo "audio/mpeg" ;;
        .ogg)   echo "audio/ogg" ;;
        .wav)   echo "audio/wav" ;;
        .flac)  echo "audio/flac" ;;
        .aac)   echo "audio/aac" ;;
        .m4a)   echo "audio/mp4" ;;
        .opus)  echo "audio/opus" ;;
        # archives
        .zip)   echo "application/zip" ;;
        .gz)    echo "application/gzip" ;;
        .tar)   echo "application/x-tar" ;;
        .7z)    echo "application/x-7z-compressed" ;;
        .bz2)   echo "application/x-bzip2" ;;
        .rar)   echo "application/vnd.rar" ;;
        # default
        *)      echo "text/plain; charset=utf-8" ;;
    esac
}

# ── Decide whether to gzip a file based on extension ──────────────────────
# Returns 0 (success) for text-like types where gzip is likely to help.
should_gzip() {
    case "$1" in
        .html|.htm|.css|.csv|.xml|.js|.json|.mjs|.map|.svg|.txt|.ttf|.otf)
            return 0 ;;
        *)
            return 1 ;;
    esac
}

# ── Collect files (recursive, exclude .DS_Store and dirs) ────────────────
files=""
if [ -d "$WWW_DIR" ]; then
    # Use find for recursive listing, sort for deterministic output
    files=$(find "$WWW_DIR" -type f -not -name '.DS_Store' | sort)
fi

# ── Generate assembly ─────────────────────────────────────────────────────
{
    echo '// Auto-generated by embed_www.sh — do not edit by hand.'
    echo '// Embeds all files from www/ into the binary data section.'
    echo '// Includes precomputed SHA-256 ETags for conditional requests.'
    echo '// Stage 4: FNV-1a hash-based lookup table.'
    echo ''
    echo '.data'
    echo '.align 4'  # 16-byte alignment for every embedded string and payload
    echo ''

    i=0
    entry_count=0
    : > "$FLAGS"  # clear the flags file

    for f in $files; do
        ext=".${f##*.}"
        # Handle files with no extension or dotfiles
        if [ "$ext" = ".$f" ] || [ "$ext" = "." ]; then
            ext=""
        fi
        ct=$(mime_type "$ext")

        echo '    .align 4'
        echo "embedded_path_${i}:"
        echo "    .asciz \"$f\""
        echo "embedded_path_${i}_end:"
        echo ''
        echo '    .align 4'
        echo "embedded_ct_${i}:"
        echo "    .asciz \"$ct\""
        echo "embedded_ct_${i}_end:"
        echo ''

        # Try gzip for text-like files
        gzipped=0
        tmp_gz=""
        if should_gzip "$ext"; then
            tmp_gz="${GZCACHEDIR}/${i}.gz"
            if gzip -c -9 -n "$f" > "$tmp_gz" 2>/dev/null; then
                # Compare sizes: use wc -c for portability
                orig_size=$(wc -c < "$f" | tr -d ' ')
                gz_size=$(wc -c < "$tmp_gz" | tr -d ' ')
                if [ "$gz_size" -lt "$orig_size" ]; then
                    gzipped=1
                fi
            fi
        fi

        # Compute FNV-1a hash of the path for hash-based lookup
        h=$(fnv1a "$f")

        # Save gzip flag and hash for the table pass
        echo "$gzipped $h" >> "$FLAGS"

        # Compute SHA-256 on the actual content that will be served
        # (gzipped if applicable, otherwise raw)
        if [ "$gzipped" -eq 1 ]; then
            sha256_hex=$($SHA256 "$tmp_gz" | cut -d' ' -f1)
        else
            sha256_hex=$($SHA256 "$f" | cut -d' ' -f1)
        fi

        # Emit ETag string (hex SHA-256 wrapped in quotes per HTTP spec)
        echo '    .align 4'
        echo "embedded_etag_${i}:"
        echo "    .asciz \"\\\"${sha256_hex}\\\"\""
        echo "embedded_etag_${i}_end:"
        echo ''

        echo '    .align 4'  # payloads start on a 16-byte boundary too
        if [ "$gzipped" -eq 1 ]; then
            echo "embedded_data_${i}:"
            echo "    .incbin \"$tmp_gz\""
            echo "embedded_data_${i}_end:"
            echo ''
        else
            echo "embedded_data_${i}:"
            echo "    .incbin \"$f\""
            echo "embedded_data_${i}_end:"
            echo ''
        fi

        i=$((i + 1))
        entry_count=$((entry_count + 1))
    done

    # Table entries are sorted lexicographically by path (files are
    # already sorted by 'find ... | sort' above), but with Stage 4 we
    # use a separate hash-based lookup table sorted by FNV-1a hash.
    echo '.align 4'
    echo '.global embedded_files'
    echo '.global embedded_count'
    echo '.global embedded_entry_size'
    echo ''
    echo '.equ embedded_entry_size, 80'
    echo "embedded_count:"
    echo "    .8byte $entry_count"
    echo ''
    echo 'embedded_files:'

    # Generate main table entries with hash at the start
    # Entry layout (80 bytes):
    #   +0:  hash        (8 bytes)
    #   +8:  path_ptr    (8 bytes)
    #   +16: path_len    (8 bytes)
    #   +24: content_ptr (8 bytes)
    #   +32: content_size (8 bytes)
    #   +40: ct_ptr      (8 bytes)
    #   +48: ct_len      (8 bytes)
    #   +56: gzip flag   (8 bytes)
    #   +64: etag_ptr    (8 bytes)
    #   +72: etag_len    (8 bytes)
    i=0
    while read -r gzflag hash; do
        printf '    .8byte %s\n' "$hash"
        printf '    .8byte embedded_path_%d, (embedded_path_%d_end - embedded_path_%d - 1)\n' "$i" "$i" "$i"
        printf '    .8byte embedded_data_%d, (embedded_data_%d_end - embedded_data_%d)\n' "$i" "$i" "$i"
        printf '    .8byte embedded_ct_%d,   (embedded_ct_%d_end - embedded_ct_%d - 1)\n' "$i" "$i" "$i"
        printf '    .8byte %d\n' "$gzflag"
        printf '    .8byte embedded_etag_%d, (embedded_etag_%d_end - embedded_etag_%d - 1)\n' "$i" "$i" "$i"
        i=$((i + 1))
    done < "$FLAGS"

    # Sentinel entry
    echo '    .8byte 0   // sentinel — end of table'

    # ── Generate hash lookup table (sorted by hash for binary search) ────
    echo ''
    echo '.align 4'
    echo '.global embedded_hash_table'
    echo '.global embedded_hash_count'
    echo ''
    echo "embedded_hash_count:"
    echo "    .8byte $entry_count"
    echo ''
    echo 'embedded_hash_table:'

    # Extract (hash, index) pairs from FLAGS, sort by hash numerically
    awk '{print $2, NR-1}' "$FLAGS" | sort -k1 -n | while read -r hash idx; do
        echo "    .8byte $hash, $idx"
    done
} > "$OUTPUT"

echo "Generated $OUTPUT with $entry_count embedded file(s)."
