#!/bin/sh
# embed_www.sh — generate src/embedded.S by embedding all www/ files into the binary.
# This script scans www/ recursively, determines MIME types by extension,
# and generates an assembly file with .incbin directives and a lookup table.
# For text-like files, gzip is applied if it reduces size; browsers will
# decompress transparently via Content-Encoding: gzip.

set -eu

WWW_DIR="www"
OUTPUT="src/embedded.S"
GZFLAGS=$(mktemp /tmp/ymawky_gzflags_XXXXXX)
trap 'rm -f "$GZFLAGS"' EXIT

# Persistent gzip cache dir — must outlive this script for the assembler.
GZCACHEDIR="www_gz"
mkdir -p "$GZCACHEDIR"

# ── MIME type map (mirrors file_types table in src/file.S) ────────────────
mime_type() {
    case "$1" in
        # web
        .html)  echo "text/html; charset=utf-8" ;;
        .htm)   echo "text/html; charset=utf-8" ;;
        .css)   echo "text/css; charset=utf-8" ;;
        .csv)   echo "text/csv; charset=utf-8" ;;
        .xml)   echo "text/xml; charset=utf-8" ;;
        .js)    echo "text/javascript; charset=utf-8" ;;
        .json)  echo "application/json" ;;
        .wasm)  echo "application/wasm" ;;
        .mjs)   echo "text/javascript; charset=utf-8" ;;
        .map)   echo "application/json" ;;
        # image
        .png)   echo "image/png" ;;
        .jpg)   echo "image/jpeg" ;;
        .jpeg)  echo "image/jpeg" ;;
        .gif)   echo "image/gif" ;;
        .svg)   echo "image/svg+xml" ;;
        .ico)   echo "image/x-icon" ;;
        .webp)  echo "image/webp" ;;
        .avif)  echo "image/avif" ;;
        .bmp)   echo "image/bmp" ;;
        .tiff)  echo "image/tiff" ;;
        .apng)  echo "image/apng" ;;
        # fonts
        .woff)  echo "font/woff" ;;
        .woff2) echo "font/woff2" ;;
        .ttf)   echo "font/ttf" ;;
        .otf)   echo "font/otf" ;;
        # documents
        .txt)   echo "text/plain; charset=utf-8" ;;
        .pdf)   echo "application/pdf" ;;
        .doc)   echo "application/msword" ;;
        .docx)  echo "application/vnd.openxmlformats-officedocument.wordprocessingml.document" ;;
        .epub)  echo "application/epub+zip" ;;
        .rtf)   echo "application/rtf" ;;
        # video
        .mp4)   echo "video/mp4" ;;
        .webm)  echo "video/webm" ;;
        .mkv)   echo "video/x-matroska" ;;
        .avi)   echo "video/x-msvideo" ;;
        .mov)   echo "video/quicktime" ;;
        # audio
        .mp3)   echo "audio/mpeg" ;;
        .ogg)   echo "audio/ogg" ;;
        .wav)   echo "audio/wav" ;;
        .flac)  echo "audio/flac" ;;
        .aac)   echo "audio/aac" ;;
        .m4a)   echo "audio/mp4" ;;
        .opus)  echo "audio/opus" ;;
        # archives
        .zip)   echo "application/zip" ;;
        .gz)    echo "application/gzip" ;;
        .tar)   echo "application/x-tar" ;;
        .7z)    echo "application/x-7z-compressed" ;;
        .bz2)   echo "application/x-bzip2" ;;
        .rar)   echo "application/vnd.rar" ;;
        # default
        *)      echo "text/plain; charset=utf-8" ;;
    esac
}

# ── Decide whether to gzip a file based on extension ──────────────────────
# Returns 0 (success) for text-like types where gzip is likely to help.
should_gzip() {
    case "$1" in
        .html|.htm|.css|.csv|.xml|.js|.json|.mjs|.map|.svg|.txt|.ttf|.otf)
            return 0 ;;
        *)
            return 1 ;;
    esac
}

# ── Collect files (recursive, exclude .DS_Store and dirs) ────────────────
files=""
if [ -d "$WWW_DIR" ]; then
    # Use find for recursive listing, sort for deterministic output
    files=$(find "$WWW_DIR" -type f -not -name '.DS_Store' | sort)
fi

# ── Generate assembly ─────────────────────────────────────────────────────
{
    echo '// Auto-generated by embed_www.sh — do not edit by hand.'
    echo '// Embeds all files from www/ into the binary data section.'
    echo ''
    echo '.data'
    echo '.align 3'
    echo ''

    i=0
    entry_count=0
    : > "$GZFLAGS"  # clear the gzip flags file

    for f in $files; do
        ext=".${f##*.}"
        # Handle files with no extension or dotfiles
        if [ "$ext" = ".$f" ] || [ "$ext" = "." ]; then
            ext=""
        fi
        ct=$(mime_type "$ext")

        echo "embedded_path_${i}:"
        echo "    .asciz \"$f\""
        echo "embedded_path_${i}_end:"
        echo ''
        echo "embedded_ct_${i}:"
        echo "    .asciz \"$ct\""
        echo "embedded_ct_${i}_end:"
        echo ''

        # Try gzip for text-like files
        gzipped=0
        tmp_gz=""
        if should_gzip "$ext"; then
            tmp_gz="${GZCACHEDIR}/${i}.gz"
            if gzip -c -9 -n "$f" > "$tmp_gz" 2>/dev/null; then
                # Compare sizes: use wc -c for portability
                orig_size=$(wc -c < "$f" | tr -d ' ')
                gz_size=$(wc -c < "$tmp_gz" | tr -d ' ')
                if [ "$gz_size" -lt "$orig_size" ]; then
                    gzipped=1
                fi
            fi
        fi

        # Save the gzip flag for the table pass
        echo "$gzipped" >> "$GZFLAGS"

        if [ "$gzipped" -eq 1 ]; then
            echo "embedded_data_${i}:"
            echo "    .incbin \"$tmp_gz\""
            echo "embedded_data_${i}_end:"
            echo ''
        else
            echo "embedded_data_${i}:"
            echo "    .incbin \"$f\""
            echo "embedded_data_${i}_end:"
            echo ''
        fi

        i=$((i + 1))
        entry_count=$((entry_count + 1))
    done

    # Table entries are sorted lexicographically by path (files are
    # already sorted by 'find ... | sort' above), enabling binary search
    # in lookup_embedded for O(log n) lookup.
    echo '.align 3'
    echo '.global embedded_files'
    echo '.global embedded_count'
    echo '.global embedded_entry_size'
    echo ''
    echo '.equ embedded_entry_size, 56'
    echo "embedded_count:"
    echo "    .8byte $entry_count"
    echo ''
    echo 'embedded_files:'

    i=0
    while read -r gzflag; do
        printf '    .8byte embedded_path_%d, (embedded_path_%d_end - embedded_path_%d - 1)\n' "$i" "$i" "$i"
        printf '    .8byte embedded_data_%d, (embedded_data_%d_end - embedded_data_%d)\n' "$i" "$i" "$i"
        printf '    .8byte embedded_ct_%d,   (embedded_ct_%d_end - embedded_ct_%d - 1)\n' "$i" "$i" "$i"
        printf '    .8byte %d\n' "$gzflag"
        i=$((i + 1))
    done < "$GZFLAGS"

    # Sentinel entry
    echo '    .8byte 0   // sentinel — end of table'
} > "$OUTPUT"

echo "Generated $OUTPUT with $entry_count embedded file(s)."
