# ymawky Linux Makefile — static ARM64 binary, zero libc dependencies.
SRCS := $(filter-out src/config.S src/defs.S src/embedded.S,$(wildcard src/*.S))
OBJS := $(SRCS:src/%.S=%.o)

CC  := gcc
AS  := as
LD  := ld

ASFLAGS :=
LDFLAGS := -e _start --static

ymawky: $(OBJS) embedded.o
	$(LD) $(OBJS) embedded.o -o ymawky $(LDFLAGS)
	rm -f $(OBJS) embedded.o

%.o: src/%.S
	$(CC) -g -O3 -c $< -o $@

src/embedded.S: embed_www.sh $(wildcard www/* www/assets/*)
	sh embed_www.sh

clean:
	rm -f ymawky *.o src/embedded.S
