// Unit tests for src/crypto/p256_point/mul_base.S
//
// GENERATED by scripts/p256_comb_derivation.py gen-test-mulb.
// Do not hand-edit. Every expected value was produced by the
// hardware-faithful Python reference and independently checked
// against the textbook affine double-and-add oracle, which is in
// turn cross-checked against the `cryptography` package (OpenSSL)
// by `p256_comb_derivation.py interop`.
//
// Includes the cases only the comb has: k = 0 and k = n (product
// is infinity -> (0,0)), scalars with many leading zero nibbles
// (the infinity-masking path), and k >= n unreduced -- which is
// what p256_ecdsa_sign_with_k actually passes, since it feeds the
// nonce straight from p256_fe_frombytes.

#include "test_harness.h"

extern void p256_point_mul_base(uint64_t outx[4], uint64_t outy[4],
                                const uint64_t k[4])
    __asm__("p256_point_mul_base");
extern void p256_point_mul(uint64_t outx[4], uint64_t outy[4],
                           const uint64_t k[4], const uint64_t inx[4],
                           const uint64_t iny[4])
    __asm__("p256_point_mul");

static const uint64_t GX[4] = {0xf4a13945d898c296ULL, 0x77037d812deb33a0ULL, 0xf8bce6e563a440f2ULL, 0x6b17d1f2e12c4247ULL};
static const uint64_t GY[4] = {0xcbb6406837bf51f5ULL, 0x2bce33576b315eceULL, 0x8ee7eb4a7c0f9e16ULL, 0x4fe342e2fe1a7f9bULL};

struct mulb_vec {
    uint64_t k[4];
    uint64_t x[4];
    uint64_t y[4];
};

#define NMULB 28
static const struct mulb_vec VECS[NMULB] = {
    {
        {0x0000000000000000ULL, 0x0000000000000000ULL, 0x0000000000000000ULL, 0x0000000000000000ULL},
        {0x0000000000000000ULL, 0x0000000000000000ULL, 0x0000000000000000ULL, 0x0000000000000000ULL},
        {0x0000000000000000ULL, 0x0000000000000000ULL, 0x0000000000000000ULL, 0x0000000000000000ULL},
    },
    {
        {0x0000000000000001ULL, 0x0000000000000000ULL, 0x0000000000000000ULL, 0x0000000000000000ULL},
        {0xf4a13945d898c296ULL, 0x77037d812deb33a0ULL, 0xf8bce6e563a440f2ULL, 0x6b17d1f2e12c4247ULL},
        {0xcbb6406837bf51f5ULL, 0x2bce33576b315eceULL, 0x8ee7eb4a7c0f9e16ULL, 0x4fe342e2fe1a7f9bULL},
    },
    {
        {0x0000000000000002ULL, 0x0000000000000000ULL, 0x0000000000000000ULL, 0x0000000000000000ULL},
        {0xa60b48fc47669978ULL, 0xc08969e277f21b35ULL, 0x8a52380304b51ac3ULL, 0x7cf27b188d034f7eULL},
        {0x9e04b79d227873d1ULL, 0xba7dade63ce98229ULL, 0x293d9ac69f7430dbULL, 0x07775510db8ed040ULL},
    },
    {
        {0x000000000000000fULL, 0x0000000000000000ULL, 0x0000000000000000ULL, 0x0000000000000000ULL},
        {0x63668c63e59b9d5fULL, 0xae03af92de3a0ef1ULL, 0xadfb378999888265ULL, 0xf0454dc6971abae7ULL},
        {0x47e59cde0d034f36ULL, 0x2a3b21ce75b5fa3fULL, 0x4e6594e51f9643e6ULL, 0xb5b93ee3592e2d1fULL},
    },
    {
        {0x0000000000000010ULL, 0x0000000000000000ULL, 0x0000000000000000ULL, 0x0000000000000000ULL},
        {0xa5eb4787e1277c6eULL, 0xcd28392eff6ca038ULL, 0x8b821c629836315fULL, 0x76a94d138a6b4185ULL},
        {0x0e9ddd724b8c5110ULL, 0x8599a0040fc78baaULL, 0x6cb0a1b5e11e8720ULL, 0xa985fe61341f260eULL},
    },
    {
        {0x0000000000000011ULL, 0x0000000000000000ULL, 0x0000000000000000ULL, 0x0000000000000000ULL},
        {0xba1abce34738a73eULL, 0x5fa68678f0d64af8ULL, 0x9c0984b66f75301aULL, 0x47776904c0f1cc3aULL},
        {0x32f787ff71f1fcdcULL, 0x81b2804428d5733fULL, 0x6231856577648e83ULL, 0xaa005ee6b5b95728ULL},
    },
    {
        {0x00000000000000ffULL, 0x0000000000000000ULL, 0x0000000000000000ULL, 0x0000000000000000ULL},
        {0xeacd1d03e5edf214ULL, 0x08e95380f1fca470ULL, 0x23a6f90249972dfdULL, 0xf44b39759a2e6db7ULL},
        {0x436a8d917a02dedeULL, 0xa2116fca81f7a4a9ULL, 0xf0a0db4eea93ff06ULL, 0xbefafccf223ca065ULL},
    },
    {
        {0xf3b9cac2fc632550ULL, 0xbce6faada7179e84ULL, 0xffffffffffffffffULL, 0xffffffff00000000ULL},
        {0xf4a13945d898c296ULL, 0x77037d812deb33a0ULL, 0xf8bce6e563a440f2ULL, 0x6b17d1f2e12c4247ULL},
        {0x3449bf97c840ae0aULL, 0xd431cca994cea131ULL, 0x711814b583f061e9ULL, 0xb01cbd1c01e58065ULL},
    },
    {
        {0xf3b9cac2fc632551ULL, 0xbce6faada7179e84ULL, 0xffffffffffffffffULL, 0xffffffff00000000ULL},
        {0x0000000000000000ULL, 0x0000000000000000ULL, 0x0000000000000000ULL, 0x0000000000000000ULL},
        {0x0000000000000000ULL, 0x0000000000000000ULL, 0x0000000000000000ULL, 0x0000000000000000ULL},
    },
    {
        {0xffffffffffffffffULL, 0xffffffffffffffffULL, 0xffffffffffffffffULL, 0xffffffffffffffffULL},
        {0x1a3d132b9db9d31aULL, 0x2c6102c49c3677ccULL, 0x1b1023179586eb53ULL, 0xf72cbd240e26c0d2ULL},
        {0xe453d93fa83408a7ULL, 0x23250ef0cdca831eULL, 0xdc0dbd91bfe7a5d2ULL, 0x43e4ca77e2a36621ULL},
    },
    {
        {0x0f0f0f0f0f0f0f0fULL, 0x0f0f0f0f0f0f0f0fULL, 0x0f0f0f0f0f0f0f0fULL, 0x0f0f0f0f0f0f0f0fULL},
        {0x35fd5e55c87a94ceULL, 0x9290fec6f055df4aULL, 0x1c1fb21192b737b3ULL, 0x8ffb7a2eaeaaf793ULL},
        {0xd527615ce2a46d99ULL, 0xc2448bd0719824d8ULL, 0xa9a3fb92122f3863ULL, 0x656ced1ba84ae54eULL},
    },
    {
        {0xf0f0f0f0f0f0f0f0ULL, 0xf0f0f0f0f0f0f0f0ULL, 0xf0f0f0f0f0f0f0f0ULL, 0xf0f0f0f0f0f0f0f0ULL},
        {0x0b2dbdbddd3d6a69ULL, 0x7484e2fb6f1ba3d1ULL, 0xf44594edcd99e124ULL, 0xec1b5435703b3a7aULL},
        {0xaaf00fb7f5217012ULL, 0x90b69cfc74ba9868ULL, 0x19c1c94c861dbff3ULL, 0x684e0383d6a12f28ULL},
    },
    {
        {0x6fa142717d43f843ULL, 0xef2705418934083fULL, 0x25f84da49e96b311ULL, 0xac6952ec50e54b79ULL},
        {0x2093229107c9c9e2ULL, 0xfe751d609eb189bcULL, 0x0511105c9721489aULL, 0x6fb913d36b91fcd1ULL},
        {0xa84250c1821a4f25ULL, 0x5aacdc7211e7ee2aULL, 0x6b4aa80587b5b35aULL, 0x5dfc4ecdc3ad9d73ULL},
    },
    {
        {0xc9b72cec68d00056ULL, 0x2ca0d558b2d770d7ULL, 0x13dc4fc6600db12eULL, 0xe9f4550907c74ba0ULL},
        {0xb5ead9525d8c4c4eULL, 0x4382d78a3ead2f68ULL, 0x3e84150d38fca22fULL, 0xf2d64282bfaac051ULL},
        {0xf0cebca7d92e70faULL, 0xc7e17cf19113cfd7ULL, 0x53ef02d0954a183dULL, 0xc3c5b78371e2a6e1ULL},
    },
    {
        {0xb9738dc91d5ca9c9ULL, 0x29a97489cacc8bbbULL, 0x4ccf64788c8e78f4ULL, 0xdbe9d2fa4670e7cdULL},
        {0x1873d8feb27d61bcULL, 0x6840e25e16abb732ULL, 0x925750e2ddb57e05ULL, 0x9f9720fb7090aa56ULL},
        {0xf7a2dc1fcbea1844ULL, 0xf6d1715f7132a3a4ULL, 0xda894ecaf7fffe17ULL, 0x170ea87bbe091f84ULL},
    },
    {
        {0x0a3562d6cfd51f8fULL, 0x97384d38052dc75bULL, 0x32604907f0978eefULL, 0x924c350fe4a388d8ULL},
        {0x7b8c09c9cf23a0c0ULL, 0x44b95c5ac4caa5b1ULL, 0xe1fd294649130275ULL, 0xab80df73f1511d05ULL},
        {0xcec983cbef138dd2ULL, 0xd834c307cd4fb7dfULL, 0x8e0073472dcc5d3bULL, 0xcbc6393b9bdeb830ULL},
    },
    {
        {0x1249fc48476f8ea5ULL, 0x85afe5f06b50e1bcULL, 0x55309d6432336848ULL, 0x1f33b91d019019bdULL},
        {0xcf621e3254edbda4ULL, 0xc64d98ef52c8fe8eULL, 0xf0435ba66e95b84eULL, 0xc5b2bf437d26092cULL},
        {0xfa7b6a1bfe0d5c2eULL, 0xdeef18b5c893a5d0ULL, 0xd72fc4bdfd387b4dULL, 0xbf5b3591ed3e10d0ULL},
    },
    {
        {0xef9bfc80ce7818d0ULL, 0x4ee6957a4e3166e3ULL, 0x91001f758a3716beULL, 0x6c610f5d4b98ec0cULL},
        {0x0fa29ca9bd4ff9f0ULL, 0x78c4985ec3c12365ULL, 0x2b54270a891b79b4ULL, 0xdcb57805a2e69768ULL},
        {0x8f73099ffdc11f6fULL, 0x82140301a10c2fe2ULL, 0x505d821f49423c3fULL, 0x29f72ea7ccb35ff9ULL},
    },
    {
        {0x9dadcca6a4fb60dbULL, 0x4347d3bef1f2ca1cULL, 0x464bf863203f0640ULL, 0xdd6c0a706667ea93ULL},
        {0x11f5ed9da1069042ULL, 0x9f5512af55223cbeULL, 0x7e1308ae8416f4c2ULL, 0x44343e89b6b36ef4ULL},
        {0xf0ed21092b895a33ULL, 0x04df66eecf806b82ULL, 0x445d4809e5e98ee1ULL, 0x5235f02ad7fbc8a1ULL},
    },
    {
        {0x16d1caf79d2ad203ULL, 0x3e9df44b75ffaf14ULL, 0x82b1282a5e3283efULL, 0x589fc551c2cca06cULL},
        {0x63cc7d3980a12156ULL, 0x926a5495eef12f25ULL, 0xa209f96eea04cdb1ULL, 0x577cfe908ae25fa9ULL},
        {0x1c7741ee656042ddULL, 0x1fe849425c6e1966ULL, 0x345e3dc9d6070e0bULL, 0x590e9f4d260aed9fULL},
    },
    {
        {0x381d73e5731ea7a6ULL, 0x8ea237c3d613cbd0ULL, 0x006058659056f06dULL, 0x5cc84c5a16bd3fa1ULL},
        {0x8ef25e0b7db557bdULL, 0x49d828c23b1f6f57ULL, 0x27e72977cb33f795ULL, 0x2a0a403c2a0bfa24ULL},
        {0x295689031a0d6b65ULL, 0x2e6f3fb085fffe63ULL, 0xaac851645aeb710eULL, 0x48914171fef69c3bULL},
    },
    {
        {0x897e52933a011fe3ULL, 0xbb551aeb037d5126ULL, 0xe617fbead8dfc649ULL, 0x5d4c6fe9b4021dc1ULL},
        {0xb11a7650ea790acaULL, 0x930acd1122ee41f1ULL, 0x4781874af574efa2ULL, 0x851782d5c7c17e4eULL},
        {0xb898825b5ee00ae3ULL, 0xa25fa168ede20de9ULL, 0xfd5b0ed0f3b19ae1ULL, 0x163a60a613b37e5cULL},
    },
    {
        {0xdf4c35ac8cf0a76cULL, 0x5862f68ccfe49962ULL, 0xc47a6c25b739aa5bULL, 0x737ca415c523542dULL},
        {0xb7eae462d9c126ebULL, 0x30e8acd98e1cbf3aULL, 0x54d76b2299d15d53ULL, 0x092beaffd125c6b1ULL},
        {0xaf531e7ab991a8a6ULL, 0xf9d35de74e664122ULL, 0xda00c54aa15c7f5aULL, 0x758a869f5690aef7ULL},
    },
    {
        {0xf42bca47afd29e23ULL, 0x48181d3157518db4ULL, 0x90612e486026b66fULL, 0xdeacd24dd83d6ea7ULL},
        {0xcd95db64706562baULL, 0x23a908ef0d4f0c64ULL, 0x21181bf1c4b0a342ULL, 0xde7c071fb2968d3fULL},
        {0xeb616c3ed31eca28ULL, 0x006d0033298b346cULL, 0xb9a10b0b9d003b15ULL, 0xf231653a4b9b32abULL},
    },
    {
        {0x0000000000000002ULL, 0x0000000000000000ULL, 0x0000000000000000ULL, 0x0000000000000000ULL},
        {0xa60b48fc47669978ULL, 0xc08969e277f21b35ULL, 0x8a52380304b51ac3ULL, 0x7cf27b188d034f7eULL},
        {0x9e04b79d227873d1ULL, 0xba7dade63ce98229ULL, 0x293d9ac69f7430dbULL, 0x07775510db8ed040ULL},
    },
    {
        {0x00000000000000bbULL, 0x0000000000000000ULL, 0x0000000000000000ULL, 0x0000000000000000ULL},
        {0x6a5496f27ebba613ULL, 0xb22e4b3fcd1bdf4fULL, 0x4a7cb71bd71d900dULL, 0x6ab19199df4cf0afULL},
        {0x587b7ca1f5cd346bULL, 0xfcca77d36d4a47a1ULL, 0x59b9eb9ce27aee73ULL, 0x1442a8079326d051ULL},
    },
    {
        {0xb874231a69b1ffd5ULL, 0x0000000000000000ULL, 0x0000000000000000ULL, 0x0000000000000000ULL},
        {0x4f1bf09a45d5dd6bULL, 0x828b48e5a0dedd8cULL, 0x03ca1f5d7289eea8ULL, 0x1bea9f83250acaf2ULL},
        {0x5caf58fe6208443cULL, 0x06c5011abbcdc045ULL, 0xd9affac44c5129bcULL, 0x5456b0a26d4e2bc9ULL},
    },
    {
        {0x9595c786ffeb826bULL, 0x518dba3f7df2be95ULL, 0x5aea96811ec0007fULL, 0x00000000000000c3ULL},
        {0xe4b29498a833d8ceULL, 0xd38e0f93b6270ec4ULL, 0x0ce3f8549dada5b1ULL, 0x766f8fedf14440aaULL},
        {0x3e590deebeb89facULL, 0xcd31ac13382177efULL, 0x377b4c0e2b01b8c4ULL, 0x58bf5ae8fb490591ULL},
    },
};

static int eq4(const uint64_t a[4], const uint64_t b[4]) {
    for (int i = 0; i < 4; i++)
        if (a[i] != b[i])
            return 0;
    return 1;
}

int main(void) {
    TEST_SUITE("p256_point_mul_base — k*G against the validated reference");

    for (int i = 0; i < NMULB; i++) {
        uint64_t x[4], y[4];
        p256_point_mul_base(x, y, VECS[i].k);
        ASSERT_EQ("k*G x matches reference", 1, eq4(x, VECS[i].x));
        ASSERT_EQ("k*G y matches reference", 1, eq4(y, VECS[i].y));
    }

    TEST_SUITE("p256_point_mul_base — agrees with generic p256_point_mul");

    for (int i = 0; i < NMULB; i++) {
        uint64_t bx[4], by[4], gx[4], gy[4];
        p256_point_mul_base(bx, by, VECS[i].k);
        p256_point_mul(gx, gy, VECS[i].k, GX, GY);
        ASSERT_EQ("comb x == double-and-add x", 1, eq4(bx, gx));
        ASSERT_EQ("comb y == double-and-add y", 1, eq4(by, gy));
    }

    test_summary();
    return 0;
}
