#!/usr/bin/env python3
"""Insert FUNC/ENDFUNC/OBJECT/ENDOBJ around every global symbol definition.

Every exported symbol in this tree is a bare label: an ELF STT_NOTYPE with
no size. Without a type and an extent, bpftrace can't attach cleanly, perf
annotate has no end to stop disassembling at, and `nm -S` reports nothing
about how big anything is. This script rewrites each definition to use the
FUNC/ENDFUNC (text) or OBJECT/ENDOBJ (data) macros from defs.S, which carry
.type/.size on ELF and collapse to a plain .global + label on Mach-O.

Extents. A symbol's body runs from its label to the first line that starts
something else, then back over any trailing blank, comment or alignment
lines (`.align` before the next label belongs to that next label, not to
this one). What "starts something else" means differs by section:

  * data (.data/.bss/rodata) — the next label of any kind. Data labels are
    distinct objects; there is no fall-through between them.
  * text (.text) — the next *global* label only. Text is full of internal
    named branch targets (L400, Lloop, read_loop, ghf_scan), and stopping
    at those would size almost every function to its first branch.

Data-emitting directives (.byte/.word/.quad/.skip/.ascii/.incbin/...) never
terminate an extent -- they *are* the body.

Symbols with an empty body are left exactly as they are, as a plain label
keeping its own .global. That covers extent sentinels (tls_cert_der_end,
which marks the end of tls_cert_der and owns no bytes) and pure
fall-through aliases, without needing a name-based heuristic -- so real
functions that merely end in `_end` (child_end, parse_header_end) are
converted like any other.

A `.global` is removed only for a symbol this script actually converted;
the macro re-emits it. Symbols that were not converted -- sentinels, and
symbols whose label lives in an #included file (h2_huffman_table) -- keep
their directive, or they would vanish from the symbol table.

Generated files are skipped: their generators emit plain labels, so any
annotation here would be blown away on the next `make assets`.

Files are edited in place; pass --check to report without writing.
"""

import argparse
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent

# A label plus whatever follows it on the same line ("buf: .skip 64 // c").
LABEL_RE = re.compile(r"^([A-Za-z_][A-Za-z0-9_.]*):(.*)$")
GLOBAL_RE = re.compile(r"^\s*\.global\s+([A-Za-z_][A-Za-z0-9_.]*)\s*(?://.*)?$")
SECTION_RE = re.compile(r"^\s*(\.text|\.data|\.bss|rodata|\.section)\b")
ALIGN_RE = re.compile(r"^\s*\.(align|balign|p2align)\b")

DATA_SECTIONS = {".data", ".bss", "rodata"}

SKIP_FILES = {
    "src/defs.S",                   # defines the macros themselves
    "src/config.S",                 # constants only
    "src/tls/record/_constants.S",  # .equ only
    # Generated -- regenerated by `make assets` from their own emitters,
    # which write plain labels. Annotating here would not survive.
    "src/embedded.S",
    "src/tls/cert_data.S",
}


def find_files():
    for sub in ("src", "scripts", "tests"):
        yield from sorted((ROOT / sub).rglob("*.S"))


def code(line):
    """The line with any trailing comment and surrounding space removed."""
    return line.split("//")[0].strip()


def section_kinds(lines):
    """Line index -> True when that line sits in a data section."""
    in_data = False
    out = []
    for line in lines:
        m = SECTION_RE.match(code(line))
        if m:
            in_data = m.group(1) in DATA_SECTIONS
        out.append(in_data)
    return out


def body_end(lines, start, is_data, globals_found):
    """Index one past the last line of the body opened at `start`.

    Scans forward to the line that begins the next thing, then walks back
    over trailing blanks, comments and alignment padding so the extent
    covers this symbol's bytes and nothing else.
    """
    stop = len(lines)
    for j in range(start + 1, len(lines)):
        stripped = code(lines[j])
        if not stripped:
            continue
        if SECTION_RE.match(stripped) or GLOBAL_RE.match(lines[j]):
            stop = j
            break
        m = LABEL_RE.match(stripped)
        if m and (is_data or m.group(1) in globals_found):
            stop = j
            break

    def trim_blanks(k):
        while k > start + 1:
            prev = lines[k - 1]
            if not prev.strip() or ALIGN_RE.match(code(prev)):
                k -= 1
                continue
            break
        return k

    stop = trim_blanks(stop)
    # A trailing comment block belongs to whatever comes next only if a
    # blank line separates it from this body; otherwise it is a
    # continuation of the last data line and stays inside the extent.
    while stop > start + 1 and lines[stop - 1].strip().startswith("//"):
        block = stop
        while block - 1 > start and lines[block - 1].strip().startswith("//"):
            block -= 1
        if lines[block - 1].strip():
            break
        stop = trim_blanks(block)
    return stop


def process(path):
    text = path.read_text()
    lines = text.split("\n")

    globals_found = {
        m.group(1) for line in lines for m in [GLOBAL_RE.match(line)] if m
    }
    if not globals_found:
        return text, []

    is_data_at = section_kinds(lines)

    # Plan every conversion before touching the list, so no index shifts
    # underneath us.
    opens = {}            # line index -> (macro, name, trailing text)
    closes = {}           # line index -> [close directive lines]
    converted = set()

    for i, line in enumerate(lines):
        m = LABEL_RE.match(line.strip())
        if not m:
            continue
        name, rest = m.group(1), m.group(2)
        if name not in globals_found or name in converted:
            continue

        is_data = is_data_at[i]
        end = body_end(lines, i, is_data, globals_found)

        # Empty body: an extent sentinel or a pure alias. Leave the label
        # and its .global alone -- a zero .size is worse than none.
        if end <= i + 1 and not code(rest):
            continue

        indent = line[: len(line) - len(line.lstrip())]
        opens[i] = (("OBJECT" if is_data else "FUNC"), name, rest)
        closes.setdefault(end, []).append(
            f"{indent}{'ENDOBJ' if is_data else 'ENDFUNC'} {name}"
        )
        converted.add(name)

    if not converted:
        return text, []

    out = []
    for i, line in enumerate(lines):
        out.extend(closes.get(i, ()))

        if i in opens:
            macro, name, rest = opens[i]
            indent = line[: len(line) - len(line.lstrip())]
            out.append(f"{indent}{macro} {name}")
            if rest.strip():
                # Keep the original column so aligned trailing comments and
                # any continuation lines below still line up.
                out.append(" " * (len(indent) + len(name) + 1) + rest)
            continue

        g = GLOBAL_RE.match(line)
        if g and g.group(1) in converted:
            continue  # the macro emits it now

        out.append(line)
    out.extend(closes.get(len(lines), ()))

    return "\n".join(out), sorted(converted)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true", help="report, don't write")
    args = ap.parse_args()

    touched = total = 0
    for path in find_files():
        rel = path.relative_to(ROOT).as_posix()
        if rel in SKIP_FILES:
            continue
        new_text, converted = process(path)
        if not converted or new_text == path.read_text():
            continue
        touched += 1
        total += len(converted)
        print(f"{rel}: {len(converted)} symbol(s)")
        if not args.check:
            path.write_text(new_text)

    verb = "would annotate" if args.check else "annotated"
    print(f"\n{verb} {total} symbol(s) across {touched} file(s)")


if __name__ == "__main__":
    sys.exit(main())
