// Unit tests for src/tls/handshake/certificate.S (PLAN.MD Phase 15)
//
// tls_certificate_write(out) -> length serializes the Certificate
// handshake message (RFC 8446 §4.4.2) around the certificate DER bytes
// embedded at build time (src/tls/cert_data.S, generated by
// certs/embed_cert.sh from certs/cert.der). Rather than hardcoding the
// certificate's bytes here — they change every time certs/generate.sh
// is re-run — this test reads certs/cert.der straight off disk and
// checks tls_certificate_write's output against it, the same way a
// real client parsing the wire message would.

#include "test_harness.h"

extern uint64_t tls_certificate_write(void *out)
    __asm__("tls_certificate_write");

#define TLS_HS_CERTIFICATE 11

static uint32_t u24be(const uint8_t *p) {
    return (uint32_t)((p[0] << 16) | (p[1] << 8) | p[2]);
}

static uint8_t cert_der[4096];
static uint64_t cert_der_len;

static void load_cert_der(void) {
    FILE *f = fopen("../../certs/cert.der", "rb");
    if (!f) {
        (void)write(2, "test_tls_certificate: cannot open certs/cert.der\n", 51);
        exit(1);
    }
    cert_der_len = (uint64_t)fread(cert_der, 1, sizeof(cert_der), f);
    fclose(f);
}

static void test_write_structure(void) {
    TEST_SUITE("tls_certificate_write — message structure");

    uint8_t out[2048];
    uint64_t len = tls_certificate_write(out);

    uint64_t cert_len = cert_der_len;
    uint64_t list_len = cert_len + 5;
    uint64_t body_len = list_len + 4;
    uint64_t expect_total = body_len + 4;

    ASSERT_EQ("total length", (int64_t)expect_total, (int64_t)len);
    ASSERT_EQ("handshake type == certificate", TLS_HS_CERTIFICATE, out[0]);
    ASSERT_EQ("handshake length field", (int64_t)body_len, (int64_t)u24be(out + 1));
    ASSERT_EQ("certificate_request_context length == 0", 0, out[4]);
    ASSERT_EQ("certificate_list length", (int64_t)list_len, (int64_t)u24be(out + 5));
    ASSERT_EQ("cert_data length", (int64_t)cert_len, (int64_t)u24be(out + 8));
    ASSERT_EQ("cert_data bytes match certs/cert.der", 0,
              memcmp(out + 11, cert_der, cert_len));

    uint64_t ext_off = 11 + cert_len;
    ASSERT_EQ("per-entry extensions length high byte", 0, out[ext_off]);
    ASSERT_EQ("per-entry extensions length low byte", 0, out[ext_off + 1]);
}

static void test_deterministic(void) {
    TEST_SUITE("tls_certificate_write — deterministic");

    uint8_t out1[2048], out2[2048];
    uint64_t len1 = tls_certificate_write(out1);
    uint64_t len2 = tls_certificate_write(out2);

    ASSERT_EQ("same length across calls", (int64_t)len1, (int64_t)len2);
    ASSERT_EQ("same bytes across calls", 0, memcmp(out1, out2, len1));
}

int main(void) {
    load_cert_der();
    test_write_structure();
    test_deterministic();
    test_summary();
    return 0;
}
